version: "3.3"
services:
  nginx:
    ports:
      - 80:80
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    depends_on:
      - web
  web:
    build:
      context: "./nextjs-web-app"
      dockerfile: "Dockerfile"   
    ports:
      - 3000:3000
